// Code generated by "stringer -type errCode -linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerErr-50001]
}

const _errCode_name = "系统错误"

var _errCode_index = [...]uint8{0, 12}

func (i errCode) String() string {
	i -= 50001
	if i < 0 || i >= errCode(len(_errCode_index)-1) {
		return "errCode(" + strconv.FormatInt(int64(i+50001), 10) + ")"
	}
	return _errCode_name[_errCode_index[i]:_errCode_index[i+1]]
}
