// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AddHostReq struct {
	Host string `json:"host"`
}

type AddHostRes struct {
}

type LoadByjsonReq struct {
	LoadJson string `json:"apps"`
}

type LoadByjsonRes struct {
}

type UpdateHostReq struct {
	OrgHost string `json:"orgHost"`
	ExpHost string `json:"expHost"`
}

type UpdateHostRes struct {
}
