// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: naming.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateHostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgHost       string                 `protobuf:"bytes,1,opt,name=orgHost,proto3" json:"orgHost,omitempty"`
	ExpHost       string                 `protobuf:"bytes,2,opt,name=expHost,proto3" json:"expHost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostReq) Reset() {
	*x = UpdateHostReq{}
	mi := &file_naming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostReq) ProtoMessage() {}

func (x *UpdateHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostReq.ProtoReflect.Descriptor instead.
func (*UpdateHostReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateHostReq) GetOrgHost() string {
	if x != nil {
		return x.OrgHost
	}
	return ""
}

func (x *UpdateHostReq) GetExpHost() string {
	if x != nil {
		return x.ExpHost
	}
	return ""
}

type UpdateHostRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostRes) Reset() {
	*x = UpdateHostRes{}
	mi := &file_naming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostRes) ProtoMessage() {}

func (x *UpdateHostRes) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostRes.ProtoReflect.Descriptor instead.
func (*UpdateHostRes) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{1}
}

type GetAllInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInfoReq) Reset() {
	*x = GetAllInfoReq{}
	mi := &file_naming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInfoReq) ProtoMessage() {}

func (x *GetAllInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInfoReq.ProtoReflect.Descriptor instead.
func (*GetAllInfoReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{2}
}

type GetAllInfoReqRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInfoReqRes) Reset() {
	*x = GetAllInfoReqRes{}
	mi := &file_naming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInfoReqRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInfoReqRes) ProtoMessage() {}

func (x *GetAllInfoReqRes) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInfoReqRes.ProtoReflect.Descriptor instead.
func (*GetAllInfoReqRes) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllInfoReqRes) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type AddHostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostReq) Reset() {
	*x = AddHostReq{}
	mi := &file_naming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostReq) ProtoMessage() {}

func (x *AddHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostReq.ProtoReflect.Descriptor instead.
func (*AddHostReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{4}
}

func (x *AddHostReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type AddHostRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostRes) Reset() {
	*x = AddHostRes{}
	mi := &file_naming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostRes) ProtoMessage() {}

func (x *AddHostRes) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostRes.ProtoReflect.Descriptor instead.
func (*AddHostRes) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{5}
}

type LoadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cfg           string                 `protobuf:"bytes,1,opt,name=cfg,proto3" json:"cfg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadReq) Reset() {
	*x = LoadReq{}
	mi := &file_naming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReq) ProtoMessage() {}

func (x *LoadReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReq.ProtoReflect.Descriptor instead.
func (*LoadReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{6}
}

func (x *LoadReq) GetCfg() string {
	if x != nil {
		return x.Cfg
	}
	return ""
}

type LoadRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRes) Reset() {
	*x = LoadRes{}
	mi := &file_naming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRes) ProtoMessage() {}

func (x *LoadRes) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRes.ProtoReflect.Descriptor instead.
func (*LoadRes) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{7}
}

var File_naming_proto protoreflect.FileDescriptor

const file_naming_proto_rawDesc = "" +
	"\n" +
	"\fnaming.proto\x12\x05greet\"C\n" +
	"\rUpdateHostReq\x12\x18\n" +
	"\aorgHost\x18\x01 \x01(\tR\aorgHost\x12\x18\n" +
	"\aexpHost\x18\x02 \x01(\tR\aexpHost\"\x0f\n" +
	"\rUpdateHostRes\"\x0f\n" +
	"\rGetAllInfoReq\"&\n" +
	"\x10GetAllInfoReqRes\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\" \n" +
	"\n" +
	"AddHostReq\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"\f\n" +
	"\n" +
	"AddHostRes\"\x1b\n" +
	"\aLoadReq\x12\x10\n" +
	"\x03cfg\x18\x01 \x01(\tR\x03cfg\"\t\n" +
	"\aLoadRes2\xd8\x01\n" +
	"\x06Naming\x12&\n" +
	"\x04Load\x12\x0e.greet.LoadReq\x1a\x0e.greet.LoadRes\x12/\n" +
	"\aAddHost\x12\x11.greet.AddHostReq\x1a\x11.greet.AddHostRes\x12;\n" +
	"\n" +
	"GetAllInfo\x12\x14.greet.GetAllInfoReq\x1a\x17.greet.GetAllInfoReqRes\x128\n" +
	"\n" +
	"UpdateHost\x12\x14.greet.UpdateHostReq\x1a\x14.greet.UpdateHostResB\n" +
	"Z\b./namingb\x06proto3"

var (
	file_naming_proto_rawDescOnce sync.Once
	file_naming_proto_rawDescData []byte
)

func file_naming_proto_rawDescGZIP() []byte {
	file_naming_proto_rawDescOnce.Do(func() {
		file_naming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naming_proto_rawDesc), len(file_naming_proto_rawDesc)))
	})
	return file_naming_proto_rawDescData
}

var file_naming_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_naming_proto_goTypes = []any{
	(*UpdateHostReq)(nil),    // 0: greet.UpdateHostReq
	(*UpdateHostRes)(nil),    // 1: greet.UpdateHostRes
	(*GetAllInfoReq)(nil),    // 2: greet.GetAllInfoReq
	(*GetAllInfoReqRes)(nil), // 3: greet.GetAllInfoReqRes
	(*AddHostReq)(nil),       // 4: greet.AddHostReq
	(*AddHostRes)(nil),       // 5: greet.AddHostRes
	(*LoadReq)(nil),          // 6: greet.LoadReq
	(*LoadRes)(nil),          // 7: greet.LoadRes
}
var file_naming_proto_depIdxs = []int32{
	6, // 0: greet.Naming.Load:input_type -> greet.LoadReq
	4, // 1: greet.Naming.AddHost:input_type -> greet.AddHostReq
	2, // 2: greet.Naming.GetAllInfo:input_type -> greet.GetAllInfoReq
	0, // 3: greet.Naming.UpdateHost:input_type -> greet.UpdateHostReq
	7, // 4: greet.Naming.Load:output_type -> greet.LoadRes
	5, // 5: greet.Naming.AddHost:output_type -> greet.AddHostRes
	3, // 6: greet.Naming.GetAllInfo:output_type -> greet.GetAllInfoReqRes
	1, // 7: greet.Naming.UpdateHost:output_type -> greet.UpdateHostRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_naming_proto_init() }
func file_naming_proto_init() {
	if File_naming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naming_proto_rawDesc), len(file_naming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_naming_proto_goTypes,
		DependencyIndexes: file_naming_proto_depIdxs,
		MessageInfos:      file_naming_proto_msgTypes,
	}.Build()
	File_naming_proto = out.File
	file_naming_proto_goTypes = nil
	file_naming_proto_depIdxs = nil
}
