// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"start/bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/caddy/AddHost",
				Handler: AddHostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/LoadByjson",
				Handler: LoadByjsonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/UpdateHost",
				Handler: UpdateHostHandler(serverCtx),
			},
		},
	)
}
