// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.4
// source: rpc/naming.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common
type IdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // id
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{0}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StringRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=Resp,proto3" json:"Resp,omitempty"` // 返回信息
}

func (x *StringRes) Reset() {
	*x = StringRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRes) ProtoMessage() {}

func (x *StringRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRes.ProtoReflect.Descriptor instead.
func (*StringRes) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{1}
}

func (x *StringRes) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type IdListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []int64 `protobuf:"varint,1,rep,packed,name=IdList,proto3" json:"IdList,omitempty"` // id列表
}

func (x *IdListReq) Reset() {
	*x = IdListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdListReq) ProtoMessage() {}

func (x *IdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdListReq.ProtoReflect.Descriptor instead.
func (*IdListReq) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{2}
}

func (x *IdListReq) GetIdList() []int64 {
	if x != nil {
		return x.IdList
	}
	return nil
}

type PageResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`         // 页码
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"` // 每页数量
	Total    int64 `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`       // 总数
}

func (x *PageResult) Reset() {
	*x = PageResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResult) ProtoMessage() {}

func (x *PageResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResult.ProtoReflect.Descriptor instead.
func (*PageResult) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{3}
}

func (x *PageResult) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResult) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResult) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NamingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              // 自增主键ID
	Naming    string `protobuf:"bytes,2,opt,name=Naming,proto3" json:"Naming,omitempty"`       // caddy的host
	CreatedAt string `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` // 创建时间
	UpdatedAt string `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` // 更新时间
	Page      int64  `protobuf:"varint,5,opt,name=Page,proto3" json:"Page,omitempty"`          // 页码
	PageSize  int64  `protobuf:"varint,6,opt,name=PageSize,proto3" json:"PageSize,omitempty"`  // 每页数量
}

func (x *NamingReq) Reset() {
	*x = NamingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingReq) ProtoMessage() {}

func (x *NamingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingReq.ProtoReflect.Descriptor instead.
func (*NamingReq) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{4}
}

func (x *NamingReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NamingReq) GetNaming() string {
	if x != nil {
		return x.Naming
	}
	return ""
}

func (x *NamingReq) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NamingReq) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *NamingReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *NamingReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type NamingInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              // 自增主键ID
	Naming    string `protobuf:"bytes,2,opt,name=Naming,proto3" json:"Naming,omitempty"`       // caddy的host
	CreatedAt string `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` // 创建时间
	UpdatedAt string `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` // 更新时间
}

func (x *NamingInfoRes) Reset() {
	*x = NamingInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamingInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingInfoRes) ProtoMessage() {}

func (x *NamingInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingInfoRes.ProtoReflect.Descriptor instead.
func (*NamingInfoRes) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{5}
}

func (x *NamingInfoRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NamingInfoRes) GetNaming() string {
	if x != nil {
		return x.Naming
	}
	return ""
}

func (x *NamingInfoRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NamingInfoRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NamingListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List       []*NamingInfoRes `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`             // 示例列表
	PageResult *PageResult      `protobuf:"bytes,2,opt,name=PageResult,proto3" json:"PageResult,omitempty"` // 分页结果
}

func (x *NamingListRes) Reset() {
	*x = NamingListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_naming_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamingListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamingListRes) ProtoMessage() {}

func (x *NamingListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_naming_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamingListRes.ProtoReflect.Descriptor instead.
func (*NamingListRes) Descriptor() ([]byte, []int) {
	return file_rpc_naming_proto_rawDescGZIP(), []int{6}
}

func (x *NamingListRes) GetList() []*NamingInfoRes {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *NamingListRes) GetPageResult() *PageResult {
	if x != nil {
		return x.PageResult
	}
	return nil
}

var File_rpc_naming_proto protoreflect.FileDescriptor

var file_rpc_naming_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x17, 0x0a, 0x05, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x23, 0x0a, 0x09, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x0a, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x9f, 0x01,
	0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4e,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x73, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x6e, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0xd2, 0x02, 0x0a, 0x06, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12,
	0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x6e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x15,
	0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x1a, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x4e,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x0d, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x44, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x2e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6e,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12,
	0x38, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12,
	0x15, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x1a, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6e,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_naming_proto_rawDescOnce sync.Once
	file_rpc_naming_proto_rawDescData = file_rpc_naming_proto_rawDesc
)

func file_rpc_naming_proto_rawDescGZIP() []byte {
	file_rpc_naming_proto_rawDescOnce.Do(func() {
		file_rpc_naming_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_naming_proto_rawDescData)
	})
	return file_rpc_naming_proto_rawDescData
}

var file_rpc_naming_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_naming_proto_goTypes = []interface{}{
	(*IdReq)(nil),         // 0: naming.IdReq
	(*StringRes)(nil),     // 1: naming.StringRes
	(*IdListReq)(nil),     // 2: naming.IdListReq
	(*PageResult)(nil),    // 3: naming.PageResult
	(*NamingReq)(nil),     // 4: naming.NamingReq
	(*NamingInfoRes)(nil), // 5: naming.NamingInfoRes
	(*NamingListRes)(nil), // 6: naming.NamingListRes
}
var file_rpc_naming_proto_depIdxs = []int32{
	5, // 0: naming.NamingListRes.List:type_name -> naming.NamingInfoRes
	3, // 1: naming.NamingListRes.PageResult:type_name -> naming.PageResult
	4, // 2: naming.naming.GetNamingList:input_type -> naming.NamingReq
	0, // 3: naming.naming.GetNamingInfo:input_type -> naming.IdReq
	5, // 4: naming.naming.AddNaming:input_type -> naming.NamingInfoRes
	0, // 5: naming.naming.DelNaming:input_type -> naming.IdReq
	2, // 6: naming.naming.BatchDelNaming:input_type -> naming.IdListReq
	5, // 7: naming.naming.UpdateNaming:input_type -> naming.NamingInfoRes
	6, // 8: naming.naming.GetNamingList:output_type -> naming.NamingListRes
	5, // 9: naming.naming.GetNamingInfo:output_type -> naming.NamingInfoRes
	1, // 10: naming.naming.AddNaming:output_type -> naming.StringRes
	1, // 11: naming.naming.DelNaming:output_type -> naming.StringRes
	1, // 12: naming.naming.BatchDelNaming:output_type -> naming.StringRes
	1, // 13: naming.naming.UpdateNaming:output_type -> naming.StringRes
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_naming_proto_init() }
func file_rpc_naming_proto_init() {
	if File_rpc_naming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_naming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamingInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_naming_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamingListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_naming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_naming_proto_goTypes,
		DependencyIndexes: file_rpc_naming_proto_depIdxs,
		MessageInfos:      file_rpc_naming_proto_msgTypes,
	}.Build()
	File_rpc_naming_proto = out.File
	file_rpc_naming_proto_rawDesc = nil
	file_rpc_naming_proto_goTypes = nil
	file_rpc_naming_proto_depIdxs = nil
}
